version: "3"

services:
  centos8-build-test:
    image: centos:latest
    container_name: centos8-build-test 
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8082:8082"
    networks:
      orchestrationNetwork:
        ipv4_address: 192.168.10.2
    volumes:
      - /var/lib/docker/volumes/centos8_build_test_home/_data:/var/centos8_build_test_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  centos8-preprod:
    image: centos:latest
    container_name: centos8-preprod
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8083:8083"
    networks:
      orchestrationNetwork:
        ipv4_address: 192.168.10.3
    volumes:
      - /var/lib/docker/volumes/centos8_preprod_home/_data:/var/centos8_preprod_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  centos8-prod:
    image: centos:latest
    container_name: centos8-prod
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8084:8084"
    networks:
      orchestrationNetwork:
        ipv4_address: 192.168.10.4
    volumes:
      - /var/lib/docker/volumes/centos8_prod_home/_data:/var/centos8_prod_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  orchestrationNetwork:
    driver: local
    ipam:
     config:
       - subnet: 192.168.10.0/16
         gateway : 192.168.10.1
